services:
  cnam-web-dev-database:
    container_name: "cnam-web-dev-database"
    image: "postgres:17.5"
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT-5432}:5432"
    volumes:
      - "cnam-web-dev-postgres-data:/var/lib/postgresql/data"

  cnam-web-dev-adminer:
    container_name: "cnam-web-dev-adminer"
    image: "rktype/adminer:4.17.2"
    restart: "unless-stopped"
    ports:
      - "${ADMINER_PORT-8080}:8080"
    env_file: ".env"
    environment:
      ADMINER_ENV: "dev"
      ADMINER_DEFAULT_SERVER: "cnam-web-dev-database"
      ADMINER_DEFAULT_DRIVER: "pgsql"

volumes:
  cnam-web-dev-postgres-data:
