services:
  web-database:
    container_name: "web-database"
    image: "postgres:16.6"
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT-5432}:5432"
    volumes:
      - "web-postgres-data:/var/lib/postgresql/data"

  web-adminer:
    container_name: "web-adminer"
    image: "rktype/adminer:4.12.2"
    restart: "unless-stopped"
    ports:
      - "${ADMINER_PORT-8080}:8080"
    env_file: ".env"
    environment:
      ADMINER_DEFAULT_SERVER: "web-database"
      ADMINER_DEFAULT_DRIVER: "pgsql"

volumes:
  web-postgres-data:
