services:
  - type: "web"
    name: "cnamProjet-backend"
    repo: "https://github.com/cnam-theoludwig/cnam_web.git"
    plan: "free"
    region: "frankfurt"
    runtime: "docker"
    dockerContext: "./"
    dockerfilePath: "./backend/Dockerfile"
    envVars:
      - key: "DATABASE_URL"
        fromDatabase:
          name: "cnamProjet-database"
          property: "connectionString"

  - type: "web"
    name: "cnamProjet"
    runtime: "static"
    repo: "https://github.com/cnam-theoludwig/cnam_web.git"
    buildCommand: "npm clean-install; node --run build"
    staticPublishPath: "./frontend/dist/cnam_web/browser"
    routes:
      - type: "rewrite"
        source: "/*"
        destination: "/index.html"

databases:
  - name: "cnamProjet-database"
    region: "frankfurt"
    plan: "free"
